const ACTIVE_INDEX = "ACTIVE_INDEX"
const GET_RECOMMEND_MOBILE = "GET_RECOMMEND_MOBILE"
const HASMORE_RECOMMEND_MOBILE = "HASMORE_RECOMMEND_MOBILE"
const HAS_MORE_MOBILE = "HAS_MORE_MOBILE"
const IS_SHOW = "IS_SHOW"
const DETAILS = "DETAILS"
export {DETAILS,IS_SHOW,ACTIVE_INDEX,GET_RECOMMEND_MOBILE,HASMORE_RECOMMEND_MOBILE,HAS_MORE_MOBILE}